### ISSUE TITLE
Display notifications that were blocked while the user was away

### ISSUE THREAD

**Issue by antlam** [mcomella/NotificationManager#7]
An idea that came from looking at our V1, the anxiety of "what did I miss?!" could be helped by seeing what notifications we blocked while active.

![prev_missed_mock1](https://cloud.githubusercontent.com/assets/1994820/18282212/f1e33408-7414-11e6-8292-c194c59ee864.png)

**Comment by antlam** [comment]
Attaching @brampitoyo 's latest 👍 

![v1 - missed notifications 2x](https://cloud.githubusercontent.com/assets/1994820/18282292/58058268-7415-11e6-89d0-97c8ab0dc157.png)

**Comment by antlam** [comment]
Talked to @mcomella , moving this to V1. Further improvements to this UX can be tracked in issue #9 for now.

To start, we simply display the notification as is, and offer a "clear all" and "back" button.

**Comment by mcomella** [comment]
@antlam We have 3 relevant items to put in the description:
1. App name
2. Notification title
3. Notification body text

What do we want to put in these fields? I'm currently doing 1 & 2, because 2 by itself doesn't always describe what the app name is, e.g. in [this demo](http://www.bennish.net/web-notifications.html), the title is "Notification <number>" and the body is, "This is the text body of the notification..." The demo works the same on desktop as it does on android.

**Comment by mcomella** [comment]
Also:
- Most recent notifications on top, or on bottom?
- We also have the posted date we could display to users.

**Comment by brampitoyo** [comment]
What if we follow the notifications pattern in Nougat, so that the icon is displayed on the left, but the app name itself is either not prominent or hidden?

This is an example of a notification list where the app name isn’t shown. We’re banking on the fact that the user is already aware of what the app stands for purely from seeing the icon.

What do you think?

![v1 - missed notifications - simple 2x](https://cloud.githubusercontent.com/assets/51007/18337099/c452fcb6-75e1-11e6-8dfd-fd4ae539debe.png)

Answering some of your questions:
- Most recent notifications should be on top
- Let’s show the posted date, because it helps user orient whether a notification came in just now, or yesterday, or last week, etc. I’ve included it in this mockup.

**Comment by mcomella** [comment]
Sure – sounds good to me. fwiw, I'm using the app icon, rather than the notification icon (which can be different, e.g. with # badges), because it's simpler.

**Comment by antlam** [comment]
+1
- Most recent up top
- include posted date (to be clear, this is when the notification originally came in right?)

**Comment by mcomella** [comment]
> include posted date (to be clear, this is when the notification originally came in right?)

Yes. For simplicity, my current implementation leaves out the date and will just provide the time, as per Bram's mock.

![screen shot 2016-09-08 at 15 31 26](https://cloud.githubusercontent.com/assets/759372/18369245/72564484-75d9-11e6-99a8-3739bbe8c915.png)

All done in one_list branch. :)
